[package]
name = "git-branch-stash"
description = "Manage snapshots of your working directory"
version = "0.6.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gitext-rs/git-branch-stash.git"
documentation = "https://github.com/gitext-rs/git-branch-stash.git"
readme = "README.md"
categories = ["command-line-interface", "development-tools"]
keywords = ["git", "cli"]
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/gitext-rs/git-branch-stash/compare/{{tag_name}}...HEAD", exactly=1},
]

[dependencies]
git2 = { version = "0.14", default-features = false, features = ["vendored-libgit2"] }
git-config-env = "0.1"
log = "0.4"
clap = { version = "3.1", features = ["derive"] }
clap-verbosity-flag = "1.0"
proc-exit = "1"
eyre = "0.6"
human-panic = "1"
yansi = "0.5.0"
concolor = "0.0.8"
concolor-clap = { version = "0.0.9", features = ["api_unstable"] }
termtree = "0.2.4"
env_logger = { version = "0.9", default-features = false, features = ["termcolor"] }
atty = "0.2"
humantime = "2"
itertools = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ignore = "0.4"
bstr = "0.2"
maplit = "1"

[dev-dependencies]
git-fixture = { version = "0.2" }
assert_fs = "1"
